### ISSUE TITLE
OCI runtime error on macos

### ISSUE THREAD

**Issue by ee7klt** [pam79/udacimak#1]
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/user123/.udacimak" to rootfs at "/root" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`

I'm getting the above error on MacOS. any idea how to resolve it?

**Comment by paapaabdullahm** [comment]
I don't use mac so can't help much. Try changing the `--volume ~/.udacimak:/root` directive to something else say `--volume ~/.my_udacimak_meta:/root` inside /usr/local/bin/udacimak and see what happens.
